image: debian/testing
packages:
  - direnv
  - file
  - shellcheck
sources:
  - https://git.sr.ht/~motiejus/bazel-zig-cc
environment:
  CC: /usr/bin/false
triggers:
  - action: email
    condition: failure
    to: motiejus+srht@jakstys.lt
tasks:
  - setup: |
      sudo apt-get purge gcc -y && sudo apt-get autoremove -y
  - lint: |
      cd bazel-zig-cc;
      shellcheck -x $(awk '/#!\/bin\/(ba)?sh/&&FNR==1{print FILENAME}' $(git ls-files))
  - test_list_toolchains: |
      cd bazel-zig-cc; . .envrc; echo "Available toolchains:"
      bazel query @zig_sdk//... | sed -En '/.*_toolchain$/ s/.*:(.*)_toolchain$/\1/p'
  - test_hello_on_toolchains: |
      cd bazel-zig-cc
      ./ci/test
