image: debian/testing
packages:
  - curl
  - file
sources:
  - https://git.sr.ht/~motiejus/bazel-zig-cc
environment:
  CC: /usr/bin/false
tasks:
  - setup: |
      curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.9.0/bazelisk-linux-amd64 \
        -o bazel
      chmod +x bazel
  #- test_default: |
  #    cd bazel-zig-cc; ../bazel run \
  #      //test:gognu
  - test_x86_64-linux-gnu: |
      cd bazel-zig-cc; ../bazel run \
           --platforms @zig_sdk//:x86_64-linux-gnu //test:gognu
      file $(./getpath @zig_sdk//:x86_64-linux-gnu //test:gognu)
  - test_x86_64-linux-musl: |
      cd bazel-zig-cc; ../bazel run \
           --platforms @zig_sdk//:x86_64-linux-musl //test:gomusl
      file $(./getpath @zig_sdk//:x86_64-linux-musl //test:gomusl)
  - test_aarch64-linux-gnu: |
      cd bazel-zig-cc; ../bazel build \
           --platforms @zig_sdk//:aarch64-linux-gnu //test:gognu
      file $(./getpath @zig_sdk//:aarch64-linux-gnu //test:gognu)
  - test_aarch64-linux-musl: |
      cd bazel-zig-cc; ../bazel build \
           --platforms @zig_sdk//:aarch64-linux-musl //test:gomusl
      file $(./getpath @zig_sdk//:aarch64-linux-musl //test:gomusl)
  #- test_macos-gnu: |
  #    cd bazel-zig-cc; ../bazel build --toolchain_resolution_debug=true \
  #      --platforms @zig_sdk//:x86_64-macos-gnu \
  #      //test:gognu
