image: debian/stable
packages:
  - direnv
  - shellcheck
  - qemu-user-static
  - binfmt-support
sources:
  - https://git.sr.ht/~motiejus/bazel-zig-cc
environment:
  CC: /usr/bin/false
triggers:
  - action: email
    condition: failure
    to: motiejus+srht@jakstys.lt
tasks:
  - setup: |
      sudo apt-get purge gcc -y && sudo apt-get autoremove -y
      sudo dpkg --add-architecture arm64
      sudo apt-get update
      sudo apt-get install libc6:arm64 -y
  - list_toolchains_platforms: |
      cd bazel-zig-cc; . .envrc
      echo "Available toolchains:"
      bazel query @zig_sdk//toolchain:*
      echo "Available platforms:"
      bazel query @zig_sdk//platform:*
  - test: |
      cd bazel-zig-cc; . .envrc
      ./ci/test --color=yes --curses=yes
  - lint: |
      cd bazel-zig-cc; . .envrc
      ./ci/lint
      git diff --exit-code
