image: debian/testing
packages:
  - curl
sources:
  - https://git.sr.ht/~motiejus/bazel-zig-cc
environment:
  CC: /usr/bin/false
tasks:
  - setup: |
      curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.9.0/bazelisk-linux-amd64 \
        -o /usr/local/bin/bazel
      chmod +x /usr/local/bin/bazel
  - test_musl: |
      bazel run --platforms @com_github_ziglang_zig//:platform_linux-x86_64-musl //test:gomusl
  - test_gnu: |
      bazel run --platforms @com_github_ziglang_zig//:platform_linux-x86_64-gnu //test:gognu
