image: debian/stable
packages:
  - direnv
  - shellcheck
  - qemu-user-static
  - binfmt-support
  - moreutils
  - file
  - wine64
sources:
  - https://git.sr.ht/~motiejus/bazel-zig-cc
environment:
  CC: /usr/bin/false
triggers:
  - action: email
    condition: failure
    to: motiejus+srht@jakstys.lt
tasks:
  - setup: |
      sudo apt-get purge gcc -y && sudo apt-get autoremove -y
      sudo dpkg --add-architecture arm64
      sudo apt-get update
      sudo apt-get install libc6:arm64 -y
  - lint: |
      cd bazel-zig-cc; . .envrc
      ./ci/lint
      git diff --exit-code
  - test_release: |
      cd bazel-zig-cc; . .envrc
      ./ci/release
  - list_toolchains_platforms: |
      cd bazel-zig-cc; . .envrc
      ./ci/list_toolchains_platforms
  - test_launcher: |
      cd bazel-zig-cc; . .envrc
      ./ci/launcher --color=yes --curses=yes
  - test: |
      cd bazel-zig-cc; . .envrc
      export BAZEL_ZIG_CC_CACHE_PREFIX=/tmp/bazel-zig-cc-2
      ./ci/test \
        --color=yes --curses=yes \
        --repo_env BAZEL_ZIG_CC_CACHE_PREFIX=$BAZEL_ZIG_CC_CACHE_PREFIX \
        --sandbox_writable_path "$BAZEL_ZIG_CC_CACHE_PREFIX"
