image: debian/testing
packages:
  - curl
sources:
  - https://git.sr.ht/~motiejus/bazel-zig-cc
environment:
  CC: /usr/bin/false
tasks:
  - setup: |
      curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.9.0/bazelisk-linux-amd64 \
        -o bazel
      chmod +x bazel
  - test_default: |
      cd bazel-zig-cc; ../bazel run \
        //test:gognu
  - test_linux-gnu: |
      cd bazel-zig-cc; ../bazel run \
        --platforms @zig_sdk//:x86_64-linux-gnu \
        //test:gognu
  - test_linux-musl: |
      cd bazel-zig-cc; ../bazel run \
        --platforms @zig_sdk//:x86_64-linux-musl \
        //test:gomusl
  #- test_macos-gnu: |
  #    cd bazel-zig-cc; ../bazel build --toolchain_resolution_debug=true \
  #      --platforms @zig_sdk//:x86_64-macos-gnu \
  #      //test:gognu
