image: debian/testing
packages:
  - curl
  - file
sources:
  - https://git.sr.ht/~motiejus/bazel-zig-cc
environment:
  CC: /usr/bin/false
tasks:
  - setup: |
      curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.9.0/bazelisk-linux-amd64 \
        -o bazel
      chmod +x bazel
  #- test_default: |
  #    cd bazel-zig-cc; ../bazel run \
  #      //test:gognu
  - test_x86_64-linux-gnu: |
      cd bazel-zig-cc; ../bazel run \
           --platforms @zig_sdk//:x86_64-linux-gnu //test:gognu
      file $(./getpath @zig_sdk//:x86_64-linux-gnu //test:gognu) | \
        tee /dev/stderr | grep -q "dynamically linked"
  - test_x86_64-linux-musl: |
      cd bazel-zig-cc; ../bazel run \
           --platforms @zig_sdk//:x86_64-linux-musl //test:gomusl
      file $(./getpath @zig_sdk//:x86_64-linux-musl //test:gomusl) | \
        tee /dev/stderr | grep -q "statically linked"
  - test_aarch64-linux-gnu: |
      cd bazel-zig-cc; ../bazel build \
           --platforms @zig_sdk//:aarch64-linux-gnu //test:gognu
      file $(./getpath @zig_sdk//:aarch64-linux-gnu //test:gognu) | \
        tee /dev/stderr | grep -q "dynamically linked"
  - test_aarch64-linux-musl: |
      cd bazel-zig-cc; ../bazel build \
           --platforms @zig_sdk//:aarch64-linux-musl //test:gomusl
      file $(./getpath @zig_sdk//:aarch64-linux-musl //test:gomusl) | \
        tee /dev/stderr | grep -q "statically linked"
  - test_x86_64-macos-gnu: |
      cd bazel-zig-cc; ../bazel build --toolchain_resolution_debug=true \
        --platforms @zig_sdk//:x86_64-macos-gnu \
        //test:gomacos
      file $(./getpath @zig_sdk//:x86_64-macos-gnu //test:gomacos) | \
        tee /dev/stderr | grep -q "Mach-O 64-bit arm64 executable"
  - test_aarch64-macos-gnu: |
      cd bazel-zig-cc; ../bazel build --toolchain_resolution_debug=true \
        --platforms @zig_sdk//:aarch64-macos-gnu \
        //test:gomacos
      file $(./getpath @zig_sdk//:aarch64-macos-gnu //test:gomacos) | \
        tee /dev/stderr | grep -q "Mach-O 64-bit x86_64 executable"
